spring.main.web-application-type=none

spring.datasource.url=jdbc:postgresql://localhost:5432/twitter
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

auth0.issuer-uri=https://dev-gtvauehvyprmkd80.us.auth0.com/
auth0.audience=https://twitter-clone-api
